kind = "api"
previewPath = "/blockerx-api"
title = "Blocker X API"
version = "1.0.0"
id = "blockerx-api-server"

[[services]]
localPort = 8090
name = "API Server"
paths = ["/blockerx-api"]

[services.development]
run = "PORT=8090 pnpm --filter @workspace/api-server run dev"

[services.env]
PORT = "8090"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/api-server", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]

[services.production.run.env]
PORT = "8090"
NODE_ENV = "production"
